// src/pages/DepartmentPage.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import { DEPARTMENTS, MOCK_PROPERTIES, MOCK_LAND_SUPPLY, MOCK_VALUATION } from '@shared/mock-data';
import AppLayout from '@/components/layout/AppLayout.vue';
import DepartmentStats from '@/components/DepartmentStats.vue';
import DataTable from '@/components/DataTable.vue';
import DataTableSkeleton from '@/components/DataTableSkeleton.vue';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
const route = useRoute();
const id = computed(() => route.params.id as string);
const department = computed(() => DEPARTMENTS.find(d => d.id === id.value));
const isLoading = ref(true);
const properties = computed(() => MOCK_PROPERTIES[id.value] || []);
const landSupply = computed(() => MOCK_LAND_SUPPLY[id.value] || []);
const valuations = computed(() => MOCK_VALUATION[id.value] || []);
const showValuation = computed(() => department.value?.id !== 'hong-kong' && department.value?.id !== 'kowloon');
watch(id, () => {
  isLoading.value = true;
  // Simulated refined hydration delay
  setTimeout(() => isLoading.value = false, 400);
}, { immediate: true });
const propertyCols = [
  { key: 'building', label: 'Building', width: 'w-[280px]' },
  { key: 'type', label: 'Type', width: 'w-[140px]' },
  { key: 'floorUnit', label: 'Unit', width: 'w-[100px]' },
  { key: 'area', label: 'Area', width: 'w-[120px]' },
  { key: 'tenant', label: 'Tenant', width: 'w-[180px]' },
  { key: 'contacts', label: 'Contacts', width: 'w-[220px]' },
];
const landCols = [
  { key: 'projectName', label: 'Project Name', width: 'w-[280px]' },
  { key: 'address', label: 'Address', width: 'w-[320px]' },
  { key: 'usage', label: 'Usage', width: 'w-[140px]' },
  { key: 'area', label: 'Area', width: 'w-[120px]' },
];
const valuationCols = [
  { key: 'address', label: 'Subject Property', width: 'w-[320px]' },
  { key: 'date', label: 'Effective Date', width: 'w-[140px]' },
  { key: 'propertyType', label: 'Asset Type', width: 'w-[140px]' },
  { key: 'valuer', label: 'Valuer', width: 'w-[180px]' },
];
</script>
<template>
  <AppLayout container>
    <div v-if="department" class="space-y-12 animate-in fade-in slide-in-from-bottom-2 duration-500">
      <div class="mb-10 text-left">
        <nav class="flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.2em] text-muted-foreground mb-3">
          <span>Global Intelligence</span>
          <span class="opacity-30">/</span>
          <span class="text-primary">{{ department.name }} Region</span>
        </nav>
        <h1 class="text-4xl md:text-5xl lg:text-6xl font-black tracking-tighter leading-none">
          {{ department.name }} <span class="text-muted-foreground/10">Explorer</span>
        </h1>
      </div>
      <div v-if="isLoading" class="space-y-12">
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div v-for="i in 3" :key="i" class="h-32 bg-muted/40 rounded-xl animate-pulse" />
        </div>
        <DataTableSkeleton />
      </div>
      <div v-else class="space-y-12">
        <DepartmentStats
          :properties="properties"
          :land-supply="landSupply"
          :valuations="valuations"
        />
        <Tabs default-value="properties" class="space-y-10">
          <TabsList class="bg-secondary/50 p-1 rounded-xl h-auto flex flex-wrap gap-1">
            <TabsTrigger value="properties" class="flex-1 py-2.5 px-6 text-[10px] font-black uppercase tracking-widest transition-all data-[state=active]:bg-background data-[state=active]:shadow-sm rounded-lg">
              Asset Inventory
            </TabsTrigger>
            <TabsTrigger value="land" class="flex-1 py-2.5 px-6 text-[10px] font-black uppercase tracking-widest transition-all data-[state=active]:bg-background data-[state=active]:shadow-sm rounded-lg">
              Development Land
            </TabsTrigger>
            <TabsTrigger v-if="showValuation" value="valuation" class="flex-1 py-2.5 px-6 text-[10px] font-black uppercase tracking-widest transition-all data-[state=active]:bg-background data-[state=active]:shadow-sm rounded-lg">
              Valuation Data
            </TabsTrigger>
          </TabsList>
          <TabsContent value="properties" class="mt-0">
            <DataTable :data="properties" :columns="propertyCols" type="property" />
          </TabsContent>
          <TabsContent value="land" class="mt-0">
            <DataTable :data="landSupply" :columns="landCols" type="land" />
          </TabsContent>
          <TabsContent v-if="showValuation" value="valuation" class="mt-0">
            <DataTable :data="valuations" :columns="valuationCols" type="valuation" />
          </TabsContent>
        </Tabs>
      </div>
    </div>
    <div v-else class="flex flex-col items-center justify-center min-h-[60vh] text-center">
      <h2 class="text-2xl font-bold mb-2">Department Not Found</h2>
      <router-link to="/" class="text-primary hover:underline">Return to Home</router-link>
    </div>
  </AppLayout>
</template>

// src/pages/DepartmentPage.tsx
import React, { useState, useEffect, useMemo } from 'react';
import { useParams, Link } from 'react-router-dom';
import { ChevronLeft, LayoutDashboard } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { DEPARTMENTS, MOCK_PROPERTIES, MOCK_LAND_SUPPLY, MOCK_VALUATION } from '@shared/mock-data';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { PropertiesTable } from '@/components/PropertiesTable';
import { LandSupplyTable } from '@/components/LandSupplyTable';
import { ValuationTable } from '@/components/ValuationTable';
import { DataTableSkeleton } from '@/components/DataTableSkeleton';
import { DepartmentStats } from '@/components/DepartmentStats';
import { AppLayout } from '@/components/layout/AppLayout';
export function DepartmentPage() {
  const { id } = useParams<{ id: string }>();
  const [isLoading, setIsLoading] = useState(true);
  const department = useMemo(() => {
    if (!id) return undefined;
    return DEPARTMENTS.find((d) => d.id === id);
  }, [id]);
  useEffect(() => {
    setIsLoading(true);
    const timer = setTimeout(() => setIsLoading(false), 400);
    return () => clearTimeout(timer);
  }, [id]);
  if (!department) {
    return (
      <div className="flex flex-col items-center justify-center h-screen space-y-6 text-center px-4">
        <div className="w-16 h-16 bg-muted rounded-full flex items-center justify-center">
          <LayoutDashboard className="w-8 h-8 text-muted-foreground" />
        </div>
        <div className="space-y-2">
          <h1 className="text-3xl font-bold tracking-tight">Department Not Found</h1>
          <p className="text-muted-foreground">The requested section could not be located in our database.</p>
        </div>
        <Link to="/" className="inline-flex items-center px-4 py-2 bg-primary text-primary-foreground rounded-md hover:opacity-90 transition-opacity">
          <ChevronLeft className="w-4 h-4 mr-2" />
          Back to Selection
        </Link>
      </div>
    );
  }
  const showValuation = department.id !== 'hong-kong' && department.id !== 'kowloon';
  const properties = MOCK_PROPERTIES[id || ''] || [];
  const landSupply = MOCK_LAND_SUPPLY[id || ''] || [];
  const valuations = MOCK_VALUATION[id || ''] || [];
  return (
    <AppLayout container contentClassName="py-0">
      <div className="space-y-10">
        <AnimatePresence mode="wait">
          {isLoading ? (
            <motion.div
              key={`loading-${id}`}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.2 }}
              className="space-y-12"
            >
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                {[1, 2, 3].map((i) => (
                  <div key={i} className="h-32 bg-muted/50 rounded-xl animate-pulse" />
                ))}
              </div>
              <DataTableSkeleton />
            </motion.div>
          ) : (
            <motion.div
              key={`content-${id}`}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}
            >
              <div className="mb-10 flex flex-col md:flex-row md:items-end justify-between gap-4">
                <div className="space-y-2">
                  <p className="text-[11px] font-black uppercase tracking-[0.4em] text-primary leading-none">
                    Institutional Intelligence
                  </p>
                  <h1 className="text-4xl md:text-5xl font-black tracking-tighter leading-none">
                    {department.name} <span className="text-muted-foreground/20">/</span> Explorer
                  </h1>
                </div>
              </div>
              <DepartmentStats
                properties={properties}
                landSupply={landSupply}
                valuations={valuations}
              />
              <Tabs defaultValue="properties" className="space-y-8">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-border/60 pb-1">
                  <TabsList className="grid w-full sm:w-auto grid-cols-2 lg:grid-cols-3 bg-secondary/60 p-1 h-auto rounded-lg">
                    <TabsTrigger value="properties" className="py-2 px-8 text-xs font-bold uppercase tracking-widest data-[state=active]:shadow-sm data-[state=active]:bg-background transition-all">
                      Properties
                    </TabsTrigger>
                    <TabsTrigger value="land" className="py-2 px-8 text-xs font-bold uppercase tracking-widest data-[state=active]:shadow-sm data-[state=active]:bg-background transition-all">
                      Land Supply
                    </TabsTrigger>
                    {showValuation && (
                      <TabsTrigger value="valuation" className="py-2 px-8 text-xs font-bold uppercase tracking-widest data-[state=active]:shadow-sm data-[state=active]:bg-background transition-all">
                        Valuation
                      </TabsTrigger>
                    )}
                  </TabsList>
                </div>
                <div className="mt-8">
                  <TabsContent value="properties" className="mt-0 ring-offset-background focus-visible:outline-none">
                    <PropertiesTable data={properties} />
                  </TabsContent>
                  <TabsContent value="land" className="mt-0 ring-offset-background focus-visible:outline-none">
                    <LandSupplyTable data={landSupply} />
                  </TabsContent>
                  {showValuation && (
                    <TabsContent value="valuation" className="mt-0 ring-offset-background focus-visible:outline-none">
                      <ValuationTable data={valuations} />
                    </TabsContent>
                  )}
                </div>
              </Tabs>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </AppLayout>
  );
}
