// src/components/DataTableSkeleton.vue
<script setup lang="ts"></script>
<template>
  <div class="space-y-6 w-full animate-pulse">
    <div class="flex justify-between items-end px-1">
      <div class="space-y-2">
        <div class="h-6 w-48 bg-muted rounded-md" />
        <div class="h-4 w-64 bg-muted/60 rounded-md" />
      </div>
      <div class="flex gap-2">
        <div class="h-9 w-24 bg-muted rounded-md" />
        <div class="h-9 w-16 bg-muted rounded-md" />
      </div>
    </div>
    <div class="border border-border rounded-xl shadow-sm overflow-hidden bg-card">
      <div class="bg-muted/40 h-12 border-b flex items-center px-4 gap-4">
        <div v-for="i in 6" :key="i" class="h-3 w-24 bg-muted-foreground/10 rounded" />
      </div>
      <div class="bg-background h-12 border-b flex items-center px-4 gap-4">
        <div v-for="i in 6" :key="i" class="h-8 w-full bg-muted/40 rounded-sm" />
      </div>
      <div class="divide-y divide-border">
        <div v-for="i in 5" :key="i" class="h-14 flex items-center px-4 gap-4">
          <div class="h-4 w-48 bg-muted/60 rounded" />
          <div class="h-4 w-20 bg-muted/40 rounded-full" />
          <div class="h-4 w-16 bg-muted/60 rounded" />
          <div class="h-4 w-16 bg-muted/60 rounded" />
          <div class="h-4 w-32 bg-muted/40 rounded" />
          <div class="h-4 w-32 bg-muted/40 rounded" />
        </div>
      </div>
    </div>
  </div>
</template>

// src/components/DataTableSkeleton.tsx
import React from 'react';
import { Skeleton } from '@/components/ui/skeleton';
import { Card } from '@/components/ui/card';
export function DataTableSkeleton() {
  return (
    <div className="space-y-6 w-full animate-in fade-in duration-500">
      <div className="flex justify-between items-end px-1">
        <div className="space-y-2">
          <Skeleton className="h-6 w-48" />
          <Skeleton className="h-4 w-64" />
        </div>
        <div className="flex gap-2">
          <Skeleton className="h-8 w-20 rounded-md" />
          <Skeleton className="h-8 w-16 rounded-md" />
        </div>
      </div>
      <Card className="border-muted shadow-soft overflow-hidden">
        <div className="overflow-x-auto">
          <div className="min-w-[1200px]">
            {/* Header Placeholder */}
            <div className="bg-muted/30 h-11 border-b flex items-center px-4 gap-4">
              {Array.from({ length: 9 }).map((_, i) => (
                <Skeleton key={i} className="h-3 w-full max-w-[100px]" />
              ))}
            </div>
            {/* Filter Row Placeholder */}
            <div className="bg-background h-12 border-b flex items-center px-2 gap-2">
              {Array.from({ length: 9 }).map((_, i) => (
                <Skeleton key={i} className="h-8 w-full rounded-sm" />
              ))}
            </div>
            {/* Rows Placeholder */}
            <div className="divide-y divide-border">
              {Array.from({ length: 8 }).map((_, i) => (
                <div key={i} className="h-14 flex items-center px-4 gap-4">
                  <Skeleton className="h-4 w-full max-w-[180px]" />
                  <Skeleton className="h-4 w-20 rounded-full" />
                  <Skeleton className="h-4 w-16" />
                  <Skeleton className="h-4 w-16" />
                  <Skeleton className="h-4 w-32" />
                  <Skeleton className="h-4 w-32" />
                  <Skeleton className="h-4 w-24" />
                  <Skeleton className="h-4 w-24" />
                  <Skeleton className="h-4 w-full" />
                </div>
              ))}
            </div>
          </div>
        </div>
      </Card>
    </div>
  );
}
