// src/components/MapModal.tsx
import React, { useState, useEffect } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { AspectRatio } from "@/components/ui/aspect-ratio";
import { Skeleton } from "@/components/ui/skeleton";
import { MapPin, ExternalLink, Loader2 } from "lucide-react";
interface MapModalProps {
  address: string;
  isOpen: boolean;
  onClose: () => void;
}
export function MapModal({ address, isOpen, onClose }: MapModalProps) {
  const [isLoaded, setIsLoaded] = useState(false);
  const encodedAddress = encodeURIComponent(address);
  const mapUrl = `https://www.google.com/maps?q=${encodedAddress}&output=embed`;
  useEffect(() => {
    if (!isOpen) {
      setIsLoaded(false);
    }
  }, [isOpen]);
  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-4xl p-0 overflow-hidden border-none shadow-2xl animate-in slide-in-from-bottom-4 duration-300">
        <DialogHeader className="p-5 border-b bg-background flex flex-row items-center justify-between space-y-0">
          <DialogTitle className="text-base font-bold flex items-center gap-2 truncate pr-4">
            <MapPin className="w-4 h-4 text-primary shrink-0" />
            <span className="truncate">{address || 'Location Explorer'}</span>
          </DialogTitle>
          <a 
            href={`https://www.google.com/maps/search/?api=1&query=${encodedAddress}`}
            target="_blank"
            rel="noopener noreferrer"
            className="text-xs font-bold uppercase tracking-tighter text-muted-foreground hover:text-primary flex items-center gap-1 shrink-0 transition-colors"
          >
            Open Maps <ExternalLink className="w-3 h-3" />
          </a>
        </DialogHeader>
        <div className="bg-muted relative group">
          <AspectRatio ratio={16 / 9} className="sm:aspect-video aspect-[4/3]">
            {!isLoaded && (
              <div className="absolute inset-0 z-10 flex flex-col items-center justify-center bg-secondary/50 backdrop-blur-sm">
                <Loader2 className="w-8 h-8 text-primary/40 animate-spin mb-2" />
                <Skeleton className="w-full h-full absolute inset-0 -z-10" />
              </div>
            )}
            {address ? (
              <iframe
                title={`Map of ${address}`}
                width="100%"
                height="100%"
                frameBorder="0"
                style={{ border: 0 }}
                src={mapUrl}
                allowFullScreen
                loading="lazy"
                onLoad={() => setIsLoaded(true)}
                referrerPolicy="no-referrer-when-downgrade"
                className="transition-opacity duration-500"
              />
            ) : (
              <div className="flex items-center justify-center h-full text-muted-foreground bg-secondary">
                <p className="font-medium">Invalid or missing address data</p>
              </div>
            )}
          </AspectRatio>
        </div>
      </DialogContent>
    </Dialog>
  );
}

// src/components/MapModal.vue
<script setup lang="ts">
import { ref, watch, onMounted } from 'vue';
import { Loader2, MapPin, ExternalLink, X } from 'lucide-vue-next';
const props = defineProps<{
  address: string;
  isOpen: boolean;
}>();
const emit = defineEmits(['onClose']);
const isLoaded = ref(false);
const encodedAddress = ref('');
watch(() => props.address, (newAddr) => {
  encodedAddress.value = encodeURIComponent(newAddr);
  isLoaded.value = false;
}, { immediate: true });
const close = () => {
  emit('onClose');
};
</script>
<template>
  <div v-if="isOpen" class="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6">
    <!-- Backdrop -->
    <div class="absolute inset-0 bg-black/60 backdrop-blur-sm animate-in fade-in duration-300" @click="close"></div>
    <!-- Content -->
    <div class="relative w-full max-w-4xl bg-background rounded-xl shadow-2xl overflow-hidden animate-in zoom-in-95 duration-200">
      <div class="flex items-center justify-between p-4 border-b">
        <div class="flex items-center gap-2 truncate pr-8">
          <MapPin class="w-4 h-4 text-primary shrink-0" />
          <h3 class="text-sm font-bold truncate tracking-tight">{{ address || 'Location Explorer' }}</h3>
        </div>
        <div class="flex items-center gap-4">
          <a
            v-if="address"
            :href="`https://www.google.com/maps/search/?api=1&query=${encodedAddress}`"
            target="_blank"
            rel="noopener noreferrer"
            class="text-[10px] font-black uppercase tracking-widest text-muted-foreground hover:text-primary flex items-center gap-1 transition-colors"
          >
            Open Maps <ExternalLink class="w-3 h-3" />
          </a>
          <button @click="close" class="p-1 hover:bg-secondary rounded-md transition-colors">
            <X class="w-4 h-4" />
          </button>
        </div>
      </div>
      <div class="relative aspect-video bg-muted overflow-hidden">
        <div v-if="!isLoaded" class="absolute inset-0 flex flex-col items-center justify-center bg-secondary/30 backdrop-blur-[2px] z-10">
          <Loader2 class="w-8 h-8 text-primary animate-spin mb-2" />
          <p class="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">Loading Map Spatial Data...</p>
        </div>
        <iframe
          v-if="address"
          :title="`Map of ${address}`"
          width="100%"
          height="100%"
          frameborder="0"
          style="border:0"
          :src="`https://www.google.com/maps?q=${encodedAddress}&output=embed`"
          allowfullscreen
          loading="lazy"
          referrerpolicy="no-referrer-when-downgrade"
          @load="isLoaded = true"
          :class="['transition-opacity duration-700', isLoaded ? 'opacity-100' : 'opacity-0']"
        ></iframe>
        <div v-else class="flex items-center justify-center h-full text-muted-foreground italic text-sm">
          No address provided for spatial preview.
        </div>
      </div>
    </div>
  </div>
</template>
